// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4tlbp3_mhuGTzIzQOFAac5MWkCq0s30g',
    appId: '1:480078142472:web:8839f9de349076364085bd',
    messagingSenderId: '480078142472',
    projectId: 'hefny-62433',
    authDomain: 'hefny-62433.firebaseapp.com',
    storageBucket: 'hefny-62433.firebasestorage.app',
    measurementId: 'G-TDE2SV9ME1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFGc6xH1F0oXD7N1N0aVNBBv_efF393M',
    appId: '1:480078142472:android:88fd568e91c35dc74085bd',
    messagingSenderId: '480078142472',
    projectId: 'hefny-62433',
    storageBucket: 'hefny-62433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZz6DnKlmejUvF1SdCz2HdwVO_8_hKixs',
    appId: '1:480078142472:ios:946be7b9345b84de4085bd',
    messagingSenderId: '480078142472',
    projectId: 'hefny-62433',
    storageBucket: 'hefny-62433.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZz6DnKlmejUvF1SdCz2HdwVO_8_hKixs',
    appId: '1:480078142472:ios:946be7b9345b84de4085bd',
    messagingSenderId: '480078142472',
    projectId: 'hefny-62433',
    storageBucket: 'hefny-62433.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4tlbp3_mhuGTzIzQOFAac5MWkCq0s30g',
    appId: '1:480078142472:web:a71551ec3de62b034085bd',
    messagingSenderId: '480078142472',
    projectId: 'hefny-62433',
    authDomain: 'hefny-62433.firebaseapp.com',
    storageBucket: 'hefny-62433.firebasestorage.app',
    measurementId: 'G-WWK3CX0FRM',
  );

}